In [20]:
# Loading the csv file to pandas dataframe
import pandas as pd
import json
df=pd.read_excel(r'C:\Users\hbhat\OneDrive\Desktop\VScode\Capstoneproject3\Datset\bangalore_cars.xlsx')
df

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1476,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1477,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1478,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1479,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1480,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [21]:
# Data processing of unstructured data into structured data by splitting data in the new car detail column into specific columns
df2 = df.copy()
df2['new_car_detail'] = df2['new_car_detail'].apply(lambda x : dict(eval(x)))
new_car_detail = df2['new_car_detail'].apply(pd.Series)
print("Length of new_car_detail", len(new_car_detail))
new_car_detail

Length of new_car_detail 1481

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,3979,VXI,â‚¹ 4 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,â‚¹ 8.11 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,â‚¹ 5.85 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,â‚¹ 4.62 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,4277,DDiS 200 Zeta,â‚¹ 7.90 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,2253,4x4 MT,â‚¹ 16.49 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,4257,Zxi BSIII,â‚¹ 3.30 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,1188,S MT,â‚¹ 4.25 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,5695,1.4 Asta Dual Tone,â‚¹ 7.50 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,1523,Asta Option AT,â‚¹ 6.75 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...

In [22]:
#Checking for null records 
new_car_detail.isnull().sum()

it                     0
ft                     0
bt                     0
km                     0
transmission           0
ownerNo                0
owner                  0
oem                    0
model                  0
modelYear              0
centralVariantId       0
variantName            0
price                  0
priceActual            0
priceSaving            0
priceFixedText      1481
trendingText           0
dtype: int64

In [23]:
# Data processing of unstructured data into structured data by splitting data in the new car overview column into specific columns
df2['new_car_overview'] = df2['new_car_overview'].apply(lambda x : dict(eval(x)))
df4 = df2['new_car_overview'].apply(pd.Series)

df5 = df4.explode('top')
flattened_info =df5['top'].apply(pd.Series)

# Restructure the DataFrame to have each key as a column
car_overview = flattened_info.pivot_table(index=flattened_info.groupby('key').cumcount(), 
                            columns='key', 
                            values='value', 
                            aggfunc='first')

print("Len of result", len(car_overview))
car_overview

Len of result 1481

key,Engine Displacement,Fuel Type,Insurance Validity,Kms Driven,Ownership,RTO,Registration Year,Seats,Transmission,Year of Manufacture
0,998 cc,Petrol,Third Party insurance,"1,20,000 Kms",Third Owner,KA51,2015,5 Seats,Manual,2015
1,1497 cc,Petrol,Comprehensive,"32,706 Kms",Second Owner,KA05,Feb 2018,5 Seats,Manual,2018
2,1199 cc,Petrol,Comprehensive,"11,949 Kms",First Owner,KA03,Sept 2018,5 Seats,Manual,2018
3,1197 cc,Petrol,Comprehensive,"17,794 Kms",First Owner,KA53,Dec 2014,5 Seats,Manual,2014
4,1248 cc,Diesel,Third Party insurance,"60,000 Kms",First Owner,KA04,2015,5 Seats,Manual,2015
...,...,...,...,...,...,...,...,...,...,...
1476,1396 cc,Diesel,Comprehensive,"1,56,039 Kms",Second Owner,NaN,NaN,5 Seats,Manual,NaN
1477,1197 cc,Petrol,Comprehensive,"56,000 Kms",Second Owner,NaN,NaN,5 Seats,Manual,NaN
1478,NaN,Petrol,NaN,"42,000 Kms",Second Owner,NaN,NaN,5 Seats,Manual,NaN
1479,NaN,Diesel,NaN,"93,003 Kms",First Owner,NaN,NaN,5 Seats,Manual,NaN
1480,NaN,Petrol,NaN,"36,000 Kms",Second Owner,NaN,NaN,NaN,Automatic,NaN

In [24]:
#Checking for null records 
car_overview.isnull().sum()

key
Engine Displacement      3
Fuel Type                0
Insurance Validity       3
Kms Driven               0
Ownership                0
RTO                    168
Registration Year        7
Seats                    1
Transmission             0
Year of Manufacture      7
dtype: int64

In [25]:
df2

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1476,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1477,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1478,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1479,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1480,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [26]:
#Splitting data in the new car features column into specific columns

#list to hold the feature lists
feature_lists = []
data_list = []

# Iterate through each record in the specified column containing the JSON data
for json_str in df2['new_car_feature']:

    json_str = json_str.replace("'",'"')
    # Parse the JSON
    data = json.loads(json_str)

    for i in data['data']:
        data_list += i['list']
    
    # Extract feature values
    features = [item['value'] for item in data_list]
    
    # Append the feature list to the main list
    feature_lists.append(features)

# Create a new DataFrame with the extracted features
df_features = pd.DataFrame({'Features': feature_lists})

# Display the new DataFrame
print(df_features)

                                               Features
0     [Power Steering, Power Windows Front, Power Wi...
1     [Power Steering, Power Windows Front, Power Wi...
2     [Power Steering, Power Windows Front, Power Wi...
3     [Power Steering, Power Windows Front, Power Wi...
4     [Power Steering, Power Windows Front, Power Wi...
...                                                 ...
1476  [Power Steering, Power Windows Front, Power Wi...
1477  [Power Steering, Power Windows Front, Power Wi...
1478  [Power Steering, Power Windows Front, Power Wi...
1479  [Power Steering, Power Windows Front, Power Wi...
1480  [Power Steering, Power Windows Front, Power Wi...

[1481 rows x 1 columns]

In [27]:
# splitting data in the new car Specifications column into specific columns
# list to hold the feature lists
specifications_list = []
data_list = []

# Iterate through each record in the specified column containing the JSON data
for json_str in df2['new_car_specs']:

    json_str = json_str.replace("'",'"')
    # Parse the JSON
    data = json.loads(json_str)

    # Add Top Specs to data_list
    data_list += data['top']

    for i in data['data']:
        data_list += i['list']
    
    # Extract feature values
    specifications = {item['key']: item['value'] for item in data_list}
    
    # Append the feature list to the main list
    specifications_list.append(specifications)

# Create a new DataFrame with the extracted features
df_specifications = pd.DataFrame(specifications_list)

# Display the new DataFrame
print(df_specifications)

         Mileage   Engine              Max Power    Torque Seats   Color  \
0      23.1 kmpl   998 CC       67.04bhp@6000rpm      90Nm     5   White
1        17 kmpl  1497 CC      121.31bhp@6500rpm     150Nm     5   White
2     23.84 kmpl  1199 CC          84bhp@6000rpm     114Nm     5     Red
3      19.1 kmpl  1197 CC       81.86bhp@6000rpm  113.75Nm     5  Others
4     23.65 kmpl  1248 CC        88.5bhp@4000rpm     200Nm     5    Gray
...          ...      ...                    ...       ...   ...     ...
1476  12.55 kmpl  2982 CC       168.5bhp@3600rpm     343Nm     7    Blue
1477     15 kmpl  1586 CC  104.68@5,600 (PS@rpm)       145     5     Red
1478   19.4 kmpl  1198 CC        86.8bhp@6000rpm     109Nm     5   White
1479  22.54 kmpl  1396 CC       88.73bhp@4000rpm   219.7Nm     5     Red
1480   18.9 kmpl  1197 CC          82bhp@6000rpm     114Nm     5   White

                   Engine Type Displacement            Max Torque  \
0                  K10B Engine          998          90Nm@3500rpm
1         Ti-VCT Petrol Engine         1497         150Nm@4500rpm
2              Revotron Engine         1199         114Nm@3500rpm
3     Kappa VTVT Petrol Engine         1197      113.75Nm@4000rpm
4       DDiS 200 Diesel Engine         1248         200Nm@1750rpm
...                        ...          ...                   ...
1476        D-4D Diesel Engine         2982    343Nm@1400-3400rpm
1477            In-Line Engine         1586   145@4,100 (kgm@rpm)
1478             i-VTEC Engine         1198         109Nm@4500rpm
1479     U2 CRDI Diesel Engine         1396  219.7Nm@1500-2750rpm
1480  Kappa VTVT Petrol Engine         1197         114Nm@4000rpm

      No of Cylinder  ...  Front Brake Type Rear Brake Type Top Speed  \
0                  3  ...   Ventilated Disc            Drum  150 Kmph
1                  3  ...   Ventilated Disc            Drum  150 Kmph
2                  3  ...              Disc            Drum  150 kmph
3                  4  ...             Disc             Drum  172km/hr
4                  4  ...   Ventilated Disc      Solid Disc  190 Kmph
...              ...  ...               ...             ...       ...
1476               4  ...   Ventilated Disc            Drum  176 Kmph
1477               4  ...   Ventilated Disc            Drum  177 kmph
1478               4  ...              Disc            Drum  164 Kmph
1479               4  ...              Disc            Drum  180 Kmph
1480               4  ...              Disc            Drum  165 Kmph

       Acceleration         Tyre Type No Door Numbers Cargo Volumn Wheel Size  \
0     15.05 Seconds  Tubeless, Radial               5   235-litres        NaN
1     15.05 Seconds   Tubeless,Radial               4   352-litres         16
2      14.3 Seconds          Tubeless               5   242-litres         14
3      14.2 Seconds   Tubeless,Radial               4   407-litres         14
4        12 Seconds   Tubeless,Radial               5   353-litres         16
...             ...               ...             ...          ...        ...
1476    9.6 Seconds   Tubeless,Radial               5   296-litres         17
1477   12.1 seconds  Tubeless, Radial               4   505 litres         16
1478   14.5 Seconds   Tubeless,Radial               5   175-litres         16
1479   11.9 Seconds          Tubeless               5   295-litres         16
1480   12.9 Seconds          Tubeless               5   256-liters         14

     Alloy Wheel Size Ground Clearance Unladen
0                 NaN                      NaN
1                  16                      NaN
2                  14                      NaN
3                  14                      NaN
4                  16                      NaN
...               ...                      ...
1476               17                    190mm
1477               16                    190mm
1478               16                    190mm
1479               16                    190mm
1480               14                    190mm

[1481 rows x 40 columns]

In [28]:
# # Adding up all data columns to singe dataframe
bangalore_cars = pd.concat([new_car_detail,car_overview,df_features,df_specifications],axis=1)
col_list = bangalore_cars.columns.to_list()
bangalore_cars.columns
# print(len(col_list))

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText',
       'Engine Displacement', 'Fuel Type', 'Insurance Validity', 'Kms Driven',
       'Ownership', 'RTO', 'Registration Year', 'Seats', 'Transmission',
       'Year of Manufacture', 'Features', 'Mileage', 'Engine', 'Max Power',
       'Torque', 'Seats', 'Color', 'Engine Type', 'Displacement', 'Max Torque',
       'No of Cylinder', 'Values per Cylinder', 'Value Configuration',
       'Fuel Suppy System', 'BoreX Stroke', 'Compression Ratio',
       'Turbo Charger', 'Super Charger', 'Length', 'Width', 'Height',
       'Wheel Base', 'Front Tread', 'Rear Tread', 'Kerb Weight',
       'Gross Weight', 'Gear Box', 'Drive Type', 'Seating Capacity',
       'Steering Type', 'Turning Radius', 'Front Brake Type',
       'Rear Brake Type', 'Top Speed', 'Acceleration', 'Tyre Type',
       'No Door Numbers', 'Cargo Volumn', 'Wheel Size', 'Alloy Wheel Size',
       'Ground Clearance Unladen'],
      dtype='object')

In [29]:
#Checking for null records 
bangalore_cars.isnull().sum()

it                          0
ft                          0
bt                          0
km                          0
transmission                0
                           ..
No Door Numbers             0
Cargo Volumn                0
Wheel Size                  1
Alloy Wheel Size            1
Ground Clearance Unladen    7
Length: 68, dtype: int64

In [25]:
bangalore_cars.to_csv(r'C:\Users\hbhat\OneDrive\Desktop\VScode\Capstoneproject3\bangalore.csv',encoding='utf-8',index=False)