In [1]:
import pandas as pd
import json 
df=pd.read_excel(r'C:\Users\hbhat\OneDrive\Desktop\VScode\Capstoneproject3\Datset\chennai_cars.xlsx')
df

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Minivans', 'k...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1414,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1415,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1416,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1417,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1418,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [2]:
# Data processing of unstructured data into structured data by splitting data in the new car detail column into specific columns
df2 = df.copy()
df2['new_car_detail'] = df2['new_car_detail'].apply(lambda x : dict(eval(x)))
new_car_detail = df2['new_car_detail'].apply(pd.Series)
print("Length of new_car_detail", len(new_car_detail))
new_car_detail

Length of new_car_detail 1419

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,8654,Turbo DCT Anniversary Edition,â‚¹ 11.50 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,4025,7 Seater Standard BSIV,â‚¹ 4.15 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
2,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,2021,8135,Turbo XV Premium BSVI,â‚¹ 7.50 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
3,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,2015,1579,Sportz 1.1L,â‚¹ 3.98 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
4,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,2015,1341,1.2 VX i VTEC,â‚¹ 5.50 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,0,Petrol,Hatchback,"42,891",Automatic,1,1st Owner,Maruti,Maruti Swift,2018,6190,AMT VXI,â‚¹ 6.20 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1415,0,Diesel,SUV,"59,100",Manual,1,1st Owner,Renault,Renault Duster,2018,5050,85PS Diesel RxZ,â‚¹ 8.90 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1416,0,Petrol,SUV,"55,913",Automatic,1,1st Owner,Tata,Tata Nexon,2018,6364,1.2 Revotron XZA Plus,â‚¹ 8.01 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1417,0,Diesel,SUV,"65,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Tiguan,2017,5849,2.0 TDI Highline,â‚¹ 20.50 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1418,0,Diesel,Sedan,"60,000",Automatic,1,1st Owner,BMW,BMW 3 Series GT,2019,6630,Sport,â‚¹ 35.75 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...

In [3]:
# Checking for null records 
new_car_detail.isnull().sum()

it                     0
ft                     0
bt                     0
km                     0
transmission           0
ownerNo                0
owner                  0
oem                    0
model                  0
modelYear              0
centralVariantId       0
variantName            0
price                  0
priceActual            0
priceSaving            0
priceFixedText      1419
trendingText           0
dtype: int64

In [4]:
# Data processing of unstructured data into structured data by splitting data in the new car overview column into specific columns
df2 = df.copy()
df2['new_car_overview'] = df2['new_car_overview'].apply(lambda x : dict(eval(x)))
df4 = df2['new_car_overview'].apply(pd.Series)

df5 = df4.explode('top')
flattened_info =df5['top'].apply(pd.Series)

# Restructure the DataFrame to have each key as a column
car_overview = flattened_info.pivot_table(index=flattened_info.groupby('key').cumcount(), 
                            columns='key', 
                            values='value', 
                            aggfunc='first')

print("Len of result", len(car_overview))
car_overview

Len of result 1419

key,Engine Displacement,Fuel Type,Insurance Validity,Kms Driven,Ownership,RTO,Registration Year,Seats,Transmission,Year of Manufacture
0,998 cc,Petrol,Third Party insurance,"20,000 Kms",First Owner,TN02,2022,5 Seats,Automatic,2022
1,1196 cc,Petrol,Comprehensive,"20,687 Kms",First Owner,TN04,Feb 2015,7 Seats,Manual,2015
2,999 cc,Petrol,Third Party insurance,"30,000 Kms",First Owner,TN22,2021,5 Seats,Manual,2021
3,1086 cc,Petrol,Comprehensive,"59,247 Kms",First Owner,TN11,May 2015,5 Seats,Manual,2015
4,1199 cc,Petrol,Third Party insurance,"50,000 Kms",First Owner,KA03,2015,5 Seats,Manual,2015
...,...,...,...,...,...,...,...,...,...,...
1414,1197 cc,Petrol,Third Party insurance,"42,891 Kms",NaN,NaN,NaN,5 Seats,Automatic,2018
1415,1461 cc,Diesel,Third Party insurance,"59,100 Kms",NaN,NaN,NaN,5 Seats,Manual,2018
1416,1198 cc,Petrol,Not Available,"55,913 Kms",NaN,NaN,NaN,5 Seats,Automatic,2018
1417,1968 cc,Diesel,Comprehensive,"65,000 Kms",NaN,NaN,NaN,5 Seats,Automatic,2017
1418,1995 cc,Diesel,Comprehensive,"60,000 Kms",NaN,NaN,NaN,5 Seats,Automatic,2019

In [5]:
#Checking for null records 
car_overview.isnull().sum()

key
Engine Displacement      0
Fuel Type                0
Insurance Validity       0
Kms Driven               0
Ownership               22
RTO                    110
Registration Year       22
Seats                    0
Transmission             0
Year of Manufacture      0
dtype: int64

In [6]:
df2

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Minivans', 'k...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1414,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1415,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1416,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1417,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1418,"{'it': 0, 'ft': 'Diesel', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [7]:
#Splitting data in the new car features column into specific columns

#list to hold the feature lists
feature_lists = []
data_list = []

# Iterate through each record in the specified column containing the JSON data
for json_str in df2['new_car_feature']:

    json_str = json_str.replace("'",'"')
    # Parse the JSON
    data = json.loads(json_str)

    data_list = []
    for i in data['data']:
        data_list += i['list']
    
    # Extract feature values
    features = [item['value'] for item in data_list]
    
    # Append the feature list to the main list
    feature_lists.append(features)

# Create a new DataFrame with the extracted features
df_features = pd.DataFrame({'Features': feature_lists})

# Display the new DataFrame
print(df_features)

                                               Features
0     [Power Steering, Power Windows Front, Power Wi...
1     [Low Fuel Warning Light, Accessory Power Outle...
2     [Power Steering, Power Windows Front, Power Wi...
3     [Power Steering, Power Windows Front, Power Wi...
4     [Power Steering, Power Windows Front, Power Wi...
...                                                 ...
1414  [Power Steering, Power Windows Front, Power Wi...
1415  [Power Steering, Power Windows Front, Power Wi...
1416  [Power Steering, Power Windows Front, Power Wi...
1417  [Power Steering, Power Windows Front, Power Wi...
1418  [Power Steering, Power Windows Front, Power Wi...

[1419 rows x 1 columns]

In [8]:
# splitting data in the new car Specifications column into specific columns
# list to hold the feature lists
specifications_list = []
data_list = []

# Iterate through each record in the specified column containing the JSON data
for json_str in df2['new_car_specs']:

    json_str = json_str.replace("'",'"')
    # Parse the JSON
    data = json.loads(json_str)

    # Add Top Specs to data_list
    data_list += data['top']

    for i in data['data']:
        data_list += i['list']
    
    # Extract feature values
    specifications = {item['key']: item['value'] for item in data_list}
    
    # Append the feature list to the main list
    specifications_list.append(specifications)

#Create a new DataFrame with the extracted features
df_specifications = pd.DataFrame(specifications_list)

# Display the new DataFrame
print(df_specifications)

       Engine          Max Power   Torque Wheel Size Seats   Color  \
0      998 CC  118.36bhp@6000rpm    172nm         16     5   Black
1     1196 CC      73bhp@6000rpm    101Nm         16     7    Grey
2      999 CC   98.63bhp@5000rpm    160Nm         16     5  Others
3     1086 CC   68.05bhp@5500rpm  99.04Nm         16     5  Silver
4     1199 CC    88.7bhp@6000rpm    110Nm         15     5  Others
...       ...                ...      ...        ...   ...     ...
1414  1197 CC   81.80bhp@6000rpm    113Nm         17     5    Blue
1415  1461 CC    83.8bhp@3750rpm    200Nm         16     5  Orange
1416  1198 CC   108.5bhp@5000rpm    170Nm         16     5   White
1417  1968 CC     141bhp@4000rpm    340Nm         18     5    Grey
1418  1995 CC     188bhp@4000rpm    400Nm         18     5   White

                                   Engine Type Displacement  \
0                     Smartstream G1.0 T - GDi          998
1                               In-Line Engine         1196
2                        HRA0 1.0 TURBO PETROL          999
3                                 IRDE2 Engine         1086
4                         i-VTEC Petrol Engine         1199
...                                        ...          ...
1414                               VTVT Engine         1197
1415                     dCi THP Diesel Engine         1461
1416         Revotron 1.2L Turbocharged engine         1198
1417              Common Rail Direct Injection         1968
1418  TwinPower Turbo 4-Cylinder Diesel Engine         1995

              Max Torque  No of Cylinder  ...  Compression Ratio  \
0     172nm@1500-4000rpm               3  ...                NaN
1          101Nm@3000rpm               4  ...              9.9:1
2     160Nm@2800-3600rpm               3  ...              9.9:1
3        99.04Nm@4500rpm               4  ...              9.9:1
4          110Nm@4800rpm               4  ...              9.9:1
...                  ...             ...  ...                ...
1414       113Nm@4200rpm               4  ...               16:1
1415       200Nm@1750rpm               4  ...               16:1
1416  170Nm@1750-4000rpm               3  ...               16:1
1417  340Nm@1750-2750rpm               4  ...               16:1
1418  400Nm@1750-2500rpm               4  ...               16:1

     Super Charger Front Tread Rear Tread Gross Weight Turning Radius  \
0              NaN         NaN        NaN          NaN            NaN
1               No      1280mm     1290mm       1540kg     4.5 metres
2               No      1280mm     1290mm       1540kg            5.0
3               No      1400mm     1385mm       1540kg     4.7 metres
4               No      1400mm     1385mm       1540kg     5.1 meters
...            ...         ...        ...          ...            ...
1414            No      1530mm     1530mm       1315kg     4.8 Meters
1415            No      1560mm     1567mm       1777kg     5.2 metres
1416            No     1540 mm    1530 mm       1777kg           5.1m
1417            No      1578mm     1568mm       2250kg     5.75meters
1418            No     1541 mm    1581 mm       2250kg     5.5 metres

        Top Speed  Acceleration  BoreX Stroke Ground Clearance Unladen
0             NaN           NaN           NaN                      NaN
1        145 Kmph  15.7 Seconds           NaN                      NaN
2        145 Kmph          11.7   72.2 x 81.3                      NaN
3        165 Kmph  14.3 Seconds   72.2 x 81.3                      NaN
4        172 Kmph  13.7 Seconds   72.2 x 81.3                      NaN
...           ...           ...           ...                      ...
1414     242 Kmph   7.5 Seconds    75 X 79 mm                    184mm
1415     156 Kmph  13.9 Seconds    75 X 79 mm                    184mm
1416  154.19 kmph  13.9 Seconds       77x85.8                   209 mm
1417  154.19 kmph  13.9 Seconds  74.5 x 81 mm                   209 mm
1418     226 Kmph   7.7 Seconds  74.5 x 81 mm                   209 mm

[1419 rows x 40 columns]

In [9]:
# Adding up all data columns to singe dataframe
Chennai_cars = pd.concat([new_car_detail,car_overview,df_features,df_specifications],axis=1)
col_list = Chennai_cars.columns.to_list()
Chennai_cars.columns
# print(len(col_list))

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText',
       'Engine Displacement', 'Fuel Type', 'Insurance Validity', 'Kms Driven',
       'Ownership', 'RTO', 'Registration Year', 'Seats', 'Transmission',
       'Year of Manufacture', 'Features', 'Engine', 'Max Power', 'Torque',
       'Wheel Size', 'Seats', 'Color', 'Engine Type', 'Displacement',
       'Max Torque', 'No of Cylinder', 'Values per Cylinder',
       'Fuel Suppy System', 'Turbo Charger', 'Length', 'Width', 'Height',
       'Wheel Base', 'Kerb Weight', 'Gear Box', 'Drive Type',
       'Seating Capacity', 'Steering Type', 'Front Brake Type',
       'Rear Brake Type', 'Tyre Type', 'Alloy Wheel Size', 'No Door Numbers',
       'Cargo Volumn', 'Mileage', 'Value Configuration', 'Compression Ratio',
       'Super Charger', 'Front Tread', 'Rear Tread', 'Gross Weight',
       'Turning Radius', 'Top Speed', 'Acceleration', 'BoreX Stroke',
       'Ground Clearance Unladen'],
      dtype='object')

In [10]:
#Checking for null records 
Chennai_cars.isnull().sum()

it                           0
ft                           0
bt                           0
km                           0
transmission                 0
                            ..
Turning Radius               1
Top Speed                    1
Acceleration                 1
BoreX Stroke                 2
Ground Clearance Unladen    15
Length: 68, dtype: int64

In [11]:
Chennai_cars.to_csv(r'C:\Users\hbhat\OneDrive\Desktop\VScode\Capstoneproject3\Chennai.csv',encoding='utf-8',index=False)