In [1]:
import pandas as pd
df=pd.read_excel(r'C:\Users\hbhat\OneDrive\Desktop\VScode\Capstoneproject3\Datset\kolkata_cars.xlsx')
df

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1376,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1377,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1378,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1379,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1380,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [2]:
# Data processing of unstructured data into structured data by splitting data in the new car detail column into specific columns
df2 = df.copy()
df2['new_car_detail'] = df2['new_car_detail'].apply(lambda x : dict(eval(x)))
new_car_detail = df2['new_car_detail'].apply(pd.Series)
print("Length of new_car_detail", len(new_car_detail))
new_car_detail

Length of new_car_detail 1381

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText
0,0,Petrol,Sedan,"70,000",Automatic,3,3rd Owner,Toyota,Toyota Camry,2014,2123,Hybrid,â‚¹ 9.75 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1,0,Petrol,Hatchback,"23,981",Manual,1,1st Owner,Datsun,Datsun RediGO,2017,5236,T Option,â‚¹ 2.66 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
2,0,Petrol,SUV,"7,100",Automatic,1,1st Owner,Renault,Renault Kiger,2021,8352,RXT AMT,â‚¹ 5.95 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
3,0,Petrol,Hatchback,"71,574",Manual,2,2nd Owner,Hyundai,Hyundai i20,2011,1642,1.2 Sportz,â‚¹ 2.23 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
4,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Audi,Audi Q3,2014,99,35 TDI Quattro Premium,â‚¹ 12 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,8682,ZXI BSVI,â‚¹ 5.10 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1377,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,3943,LXI,â‚¹ 1.80 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1378,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,4672,C 200 CGI Elegance,â‚¹ 5.50 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1379,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,4144,ZXi,â‚¹ 1.40 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...
1380,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,5048,110PS Diesel RxZ AWD,â‚¹ 5 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...

In [3]:
new_car_detail.isnull().sum()

it                     0
ft                     0
bt                     0
km                     0
transmission           0
ownerNo                0
owner                  0
oem                    0
model                  0
modelYear              0
centralVariantId       0
variantName            0
price                  0
priceActual            0
priceSaving            0
priceFixedText      1381
trendingText           0
dtype: int64

In [4]:
#  Data processing of unstructured data into structured data by splitting data in the new car overview column into specific columns
df2 = df.copy()
df2['new_car_overview'] = df2['new_car_overview'].apply(lambda x : dict(eval(x)))
df4 = df2['new_car_overview'].apply(pd.Series)

df5 = df4.explode('top')
flattened_info =df5['top'].apply(pd.Series)

# Restructure the DataFrame to have each key as a column
car_overview = flattened_info.pivot_table(index=flattened_info.groupby('key').cumcount(), 
                            columns='key', 
                            values='value', 
                            aggfunc='first')


print("Len of result", len(car_overview))
car_overview

Len of result 1381

key,Engine Displacement,Fuel Type,Insurance Validity,Kms Driven,Ownership,RTO,Registration Year,Seats,Transmission,Year of Manufacture
0,2494 cc,Petrol,Third Party insurance,"70,000 Kms",Third Owner,WB02,2014,5 Seats,Automatic,2014
1,799 cc,Petrol,Comprehensive,"23,981 Kms",First Owner,WB24,Jul 2017,5 Seats,Manual,2017
2,999 cc,Petrol,Comprehensive,"7,100 Kms",First Owner,WB06,Nov 2021,5 Seats,Automatic,2021
3,1197 cc,Petrol,Third Party,"71,574 Kms",Second Owner,WB06,Feb 2012,5 Seats,Manual,2011
4,1968 cc,Diesel,Third Party insurance,"50,000 Kms",Second Owner,WB02,2014,5 Seats,Automatic,2014
...,...,...,...,...,...,...,...,...,...,...
1376,998 cc,Petrol,Third Party insurance,"10,000 Kms",Second Owner,NaN,NaN,5 Seats,Manual,2014
1377,796 cc,Petrol,Third Party insurance,"1,20,000 Kms",NaN,NaN,NaN,5 Seats,Manual,2011
1378,1796 cc,Petrol,Third Party insurance,"50,000 Kms",NaN,NaN,NaN,NaN,Automatic,2012
1379,1197 cc,Petrol,Third Party insurance,"40,000 Kms",NaN,NaN,NaN,NaN,Manual,2017
1380,1461 cc,Diesel,Third Party insurance,"1,20,000 Kms",NaN,NaN,NaN,NaN,Manual,NaN

In [5]:
df2

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1376,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1377,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1378,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1379,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1380,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [6]:
# Splitting data in the new car features column into specific columns

import json
df2 = df.copy() 

# list to hold the feature lists
feature_lists = []
data_list = []

# Iterate through each record in the specified column containing the JSON data
for json_str in df2['new_car_feature']:

    json_str = json_str.replace("'",'"')
    # Parse the JSON
    data = json.loads(json_str)

    data_list = []
    for i in data['data']:
        data_list += i['list']
    
    # Extract feature values
    
    features = [item['value'] for item in data_list]
    
    # Append the feature list to the main list
    feature_lists.append(features)

# Create a new DataFrame with the extracted features
df_features = pd.DataFrame({'Features': feature_lists})

# Display the new DataFrame
print(df_features)

                                               Features
0     [Power Steering, Power Windows Front, Power Wi...
1     [Power Steering, Power Windows Front, Remote T...
2     [Power Steering, Power Windows Front, Power Wi...
3     [Power Steering, Power Windows Front, Power Wi...
4     [Power Steering, Power Windows Front, Power Wi...
...                                                 ...
1376  [Power Steering, Power Windows Front, Power Wi...
1377  [Power Steering, Power Windows Front, Remote T...
1378  [Power Steering, Power Windows Front, Power Wi...
1379  [Power Steering, Power Windows Front, Power Wi...
1380  [Power Steering, Power Windows Front, Power Wi...

[1381 rows x 1 columns]

In [7]:
#  Splitting data in the new car features column into specific columns
import json
df2 = df.copy() 

# list to hold the feature lists
specifications_list = []
data_list = []

# Step 3: Iterate through each record in the specified column containing the JSON data
for json_str in df2['new_car_specs']:

    json_str = json_str.replace("'",'"')
    # Parse the JSON
    data = json.loads(json_str)

    # Add Top Specs to data_list
    data_list += data['top']

    for i in data['data']:
        data_list += i['list']
    
    # Extract feature values
    specifications = {item['key']: item['value'] for item in data_list}
    
    # Append the feature list to the main list
    specifications_list.append(specifications)

# Create a new DataFrame with the extracted features
df_specifications = pd.DataFrame(specifications_list)

# Display the new DataFrame
print(df_specifications)

         Mileage   Engine          Max Power                 Torque  \
0     19.16 kmpl  2494 CC   158.2bhp@5700rpm                  213Nm
1      22.7 kmpl   799 CC   53.64bhp@5678rpm                   72Nm
2     19.03 kmpl   999 CC   71.01bhp@6250rpm                   96Nm
3        17 kmpl  1197 CC  80 PS at 5200 rpm  11.4 kgm at 4,000 rpm
4     15.73 kmpl  1968 CC  174.33bhp@4200rpm                  380Nm
...          ...      ...                ...                    ...
1376  25.24 kmpl   998 CC   65.71bhp@5500rpm                   89Nm
1377  22.74 kmpl   796 CC    47.3bhp@6000rpm                   69Nm
1378  11.74 kmpl  1796 CC     186bhp@5600rpm                  285Nm
1379   18.5 kmpl  1197 CC   85.80bhp@6000rpm                  114Nm
1380  19.72 kmpl  1461 CC  108.45bhp@4000rpm                  245Nm

     Wheel Size Seats   Color             Engine Type Displacement  \
0            17     5   White  2AR FXE Petrol Engine          2494
1            17     5     Red      0.8L Petrol Engine          799
2            17     5    Blue             1.0L energy          999
3            14     5     Red          In-Line Engine         1197
4            16     5   White       TDI Diesel Engine         1968
...         ...   ...     ...                     ...          ...
1376         13     5  Others                    K10C          998
1377         13     5  Others       F8D Petrol Engine          796
1378         17     5  Others  Blue Efficiency Engine         1796
1379         14     5  Others  K Series Petrol Engine         1197
1380         16     5  Others   dCi THP Diesel Engine         1461

                 Max Torque  ...  Front Brake Type  Rear Brake Type  \
0             213Nm@4500rpm  ...   Ventilated Disc       Solid Disc
1              72Nm@4386rpm  ...              Disc             Drum
2              96Nm@3500rpm  ...              Disc             Drum
3     11.4 kgm at 4,000 rpm  ...              Disc             Drum
4        380Nm@1750-2500rpm  ...   Ventilated Disc             Drum
...                     ...  ...               ...              ...
1376           89Nm@3500rpm  ...   Ventilated Disc             Drum
1377           69Nm@3500rpm  ...        Solid Disc             Drum
1378     285Nm@2400-4000rpm  ...   Ventilated Disc       Solid Disc
1379          114Nm@4000rpm  ...   Ventilated Disc             Drum
1380          245Nm@1750rpm  ...              Disc             Drum

             Tyre Type Alloy Wheel Size No Door Numbers  \
0      Tubeless,Radial               17               4
1      Tubeless,Radial               17               5
2     Tubeless, Radial               17               5
3      Tubeless,Radial               14               5
4      Tubeless,Radial               16               5
...                ...              ...             ...
1376  Tubeless, Radial               13               5
1377    Tubeless Tyres               13               5
1378   Tubeless,Radial               17               4
1379   Tubeless,Radial               14               5
1380   Tubeless,Radial               16               5

     Ground Clearance Unladen Cargo Volumn Compression Ratio   Acceleration  \
0                         NaN          NaN               NaN            NaN
1                       185mm          222               NaN            NaN
2                       185mm          405               NaN            NaN
3                       185mm      295 Lit                :1      12.96 Sec
4                       185mm   460-litres                :1    8.2 Seconds
...                       ...          ...               ...            ...
1376                    190mm          313             8.9:1   16.2 seconds
1377                    190mm   177-litres             8.9:1     19 Seconds
1378                    190mm   475-litres             9.3:1    8.8 Seconds
1379                    190mm   236-liters             9.3:1     15 Seconds
1380                    190mm   410-litres             9.3:1  14.20 Seconds

     Top Speed
0          NaN
1          NaN
2          NaN
3          NaN
4     212 Kmph
...        ...
1376  141km/hr
1377  140 kmph
1378  230km/hr
1379  156 Kmph
1380  168 Kmph

[1381 rows x 40 columns]

In [8]:
# Adding up all data columns to singe dataframe
Kolkata_cars = pd.concat([new_car_detail,car_overview,df_features,df_specifications],axis=1)
col_list =Kolkata_cars.columns.to_list()
Kolkata_cars.columns
# print(len(col_list))

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText',
       'Engine Displacement', 'Fuel Type', 'Insurance Validity', 'Kms Driven',
       'Ownership', 'RTO', 'Registration Year', 'Seats', 'Transmission',
       'Year of Manufacture', 'Features', 'Mileage', 'Engine', 'Max Power',
       'Torque', 'Wheel Size', 'Seats', 'Color', 'Engine Type', 'Displacement',
       'Max Torque', 'No of Cylinder', 'Values per Cylinder',
       'Value Configuration', 'Fuel Suppy System', 'BoreX Stroke',
       'Turbo Charger', 'Super Charger', 'Length', 'Width', 'Height',
       'Wheel Base', 'Front Tread', 'Rear Tread', 'Kerb Weight',
       'Gross Weight', 'Gear Box', 'Drive Type', 'Seating Capacity',
       'Steering Type', 'Turning Radius', 'Front Brake Type',
       'Rear Brake Type', 'Tyre Type', 'Alloy Wheel Size', 'No Door Numbers',
       'Ground Clearance Unladen', 'Cargo Volumn', 'Compression Ratio',
       'Acceleration', 'Top Speed'],
      dtype='object')

In [9]:
# Loading the required data to csv file for each cities
Kolkata_cars.to_csv(r'C:\Users\hbhat\OneDrive\Desktop\VScode\Capstoneproject3\Kolkata.csv',encoding='utf-8',index=False)